apiVersion: v1
kind: Service
metadata:
  name: ai-platform-api
  labels:
    app: ai-platform-api
spec:
  type: ClusterIP
  selector:
    app: ai-platform-api
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
